Repository puppetlabs/puppetlabs-node_encrypt, pull requests merged in 2023-06, with the labels that each got.

#96 (CONT-1042) - Remove unsupported OS
  metadata.json
Labels: backwards-incompatible

#97 (CONT-1042) - Add Support for Ubuntu 22.04
  metadata.json
Labels: feature

#95 (CONT-1041) - Add Puppet 8 Support/Drop Puppet 6 Support
  metadata.json
Labels: backwards-incompatible

#94 (CONT-1048) - Removal of deprecated node_encrypt::file defined type
  Gemfile
  README.md
  REFERENCE.md
  functions/secret.pp
  manifests/file.pp
  spec/defines/file_spec.rb
Labels: backwards-incompatible

#98 (maint) - add link to original module
  README.md
Labels: maintenance

#100 CONT-990_Adding PR template
  .github/pull_request_template.md
Labels: maintenance
